/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BAI_TAP_MAU_CRUD_SINHVIEN;

/**
 *
 * @author Dungna89
 */
public class Main extends javax.swing.JFrame {

  /**
   * Creates new form Main
   */
  public Main() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
   * code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jTextField1 = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jTextField2 = new javax.swing.JTextField();
    jRadioButton1 = new javax.swing.JRadioButton();
    jRadioButton2 = new javax.swing.JRadioButton();
    jRadioButton3 = new javax.swing.JRadioButton();
    jComboBox1 = new javax.swing.JComboBox<>();
    jTextField3 = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jTextField4 = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel1.setText("Tên:");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

    jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jButton1.setText("Xóa");
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

    jTextField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jTextField1.setText("jTextField1");
    getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null}
      },
      new String [] {
        "STT", "Id", "Tên", "Sđt", "Msv", "Giới Tính", "Ngành Học"
      }
    ));
    jScrollPane1.setViewportView(jTable1);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 930, -1));

    jButton2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jButton2.setText("Sửa");
    getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

    jButton3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jButton3.setText("Thêm");
    getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

    jButton4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jButton4.setText("Fake Data");
    getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

    jButton5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jButton5.setText("Tìm kiếm");
    getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, -1, -1));

    jTextField2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jTextField2.setText("jTextField1");
    getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

    jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jRadioButton1.setText("NAM");
    getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

    jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jRadioButton2.setText("Nữ");
    getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

    jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jRadioButton3.setText("Không xác định");
    getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

    jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

    jTextField3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jTextField3.setText("jTextField1");
    getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel2.setText("QUẢN LÝ SINH VIÊN JAVA 2");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 15, -1, -1));

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel3.setText("ID:");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

    jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel4.setText("Sdt:");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

    jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel5.setText("Msv:");
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

    jTextField4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jTextField4.setText("jTextField1");
    getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

    jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel6.setText("Ngành học:");
    getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

    jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jLabel7.setText("Giới tính:");
    getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Main().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JRadioButton jRadioButton1;
  private javax.swing.JRadioButton jRadioButton2;
  private javax.swing.JRadioButton jRadioButton3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField4;
  // End of variables declaration//GEN-END:variables
}
