/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BAI2_JAVA_SWING;

/**
 *
 * @author Dungna89
 */
public class B2_JFrameButton extends javax.swing.JFrame {

  /**
   * Creates new form B2_JFrameButton
   */
  public B2_JFrameButton() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this
   * code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    lbl_setTen = new javax.swing.JLabel();
    btn_BamVaoDayNhe = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jButton1.setText("RED");

    jButton2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jButton2.setText("GREEN");

    jButton3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    jButton3.setText("BLACK");

    lbl_setTen.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    lbl_setTen.setText("jLabel1");

    btn_BamVaoDayNhe.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    btn_BamVaoDayNhe.setText("BẤM VÀO ĐÂY NHÉ");
    btn_BamVaoDayNhe.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_BamVaoDayNheActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(72, 72, 72)
        .addComponent(btn_BamVaoDayNhe)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButton3)
          .addComponent(jButton2)
          .addComponent(jButton1))
        .addGap(138, 138, 138))
      .addGroup(layout.createSequentialGroup()
        .addGap(134, 134, 134)
        .addComponent(lbl_setTen)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addGap(177, 177, 177)
            .addComponent(btn_BamVaoDayNhe)
            .addGap(22, 22, 22))
          .addGroup(layout.createSequentialGroup()
            .addGap(73, 73, 73)
            .addComponent(lbl_setTen)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1)
            .addGap(30, 30, 30)))
        .addComponent(jButton2)
        .addGap(46, 46, 46)
        .addComponent(jButton3)
        .addContainerGap(127, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_BamVaoDayNheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BamVaoDayNheActionPerformed
    System.out.println("Nút đã bấm vào rồi nè");
    lbl_setTen.setText("Chào các bạn nhé!");
  }//GEN-LAST:event_btn_BamVaoDayNheActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(B2_JFrameButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(B2_JFrameButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(B2_JFrameButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(B2_JFrameButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new B2_JFrameButton().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_BamVaoDayNhe;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JLabel lbl_setTen;
  // End of variables declaration//GEN-END:variables
}
