/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DemoChayChu;

import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dungna29
 */
public class MainChayChu extends javax.swing.JFrame {

    /**
     * Creates new form MainChayChu
     */
    public MainChayChu() {
        initComponents();
        viDu1ChayTungChu();
        viDu2ChayTungTu();
        System.out.println(lbl_Name.getText().substring(0, lbl_Name.getText().length() - 1));
    }

    void viDu1ChayTungChu() {
        Thread t1 = new Thread() {
            @Override
            public void run() {
                int temp = 0;
                String txt = lbl_Name.getText();//UDPM JAVA
                while (true) {
                    try {

                        String chuCuoiCung = String.valueOf(txt.charAt(txt.length() - 1));//A
                        String chuoiMoi = chuCuoiCung + txt.substring(0, txt.length() - 1);//AUDPM JAV
                        sleep(1000);
                        txt = chuoiMoi;

                    } catch (InterruptedException ex) {
                    }
                    lbl_Name.setText(txt);
                }
            }

        };
        t1.start();
    }

    void viDu2ChayTungTu() {
        Thread t2 = new Thread() {
            String txt;
            @Override
            public void run() {
                while (true) {
                    try {
                        txt = lbl_Name2.getText();//UDPM JAVA SP22
                        String[] arrTxt = txt.split("\\s+");//Đưa chuỗi về mảng
                        String chuCuoiCung = arrTxt[arrTxt.length - 1];//SP22
                        String chuoiMoi = chuCuoiCung + " ";
                        for (int i = 0; i < arrTxt.length - 1; i++) {
                            chuoiMoi += arrTxt[i] + " ";
                        }
                        sleep(1000);
                        txt = chuoiMoi;

                    } catch (InterruptedException ex) {
                    }
                    lbl_Name2.setText(txt);
                }
            }

        };
        t2.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Name = new javax.swing.JLabel();
        lbl_Name2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Name.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        lbl_Name.setForeground(new java.awt.Color(0, 0, 255));
        lbl_Name.setText("UDPM JAVA");

        lbl_Name2.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        lbl_Name2.setForeground(new java.awt.Color(0, 0, 255));
        lbl_Name2.setText("UDPM JAVA SP22");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Name2)
                    .addComponent(lbl_Name))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lbl_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Name2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainChayChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainChayChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainChayChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainChayChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainChayChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_Name2;
    // End of variables declaration//GEN-END:variables
}
